import "./globals.css";
import FooterSection from "@/components/layout/Footer";
import NavbarSection from "@/components/layout/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased flex flex-col min-h-screen">
        <NavbarSection/>
        <section className="container max-w-9/10 mx-auto p-6 grow">
          {children}
        </section>
        <FooterSection/>
      </body>
    </html>
  );
}
